openapi: 3.2.0
info:
  contact:
    name: https://docs.yugabyte.com
  description: ALPHA - NOT FOR EXTERNAL USE
  license:
    name: Polyform Free Trial License 1.0.0
    url: https://github.com/yugabyte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt
  termsOfService: TODO(chirag)
  title: YugabyteDB Anywhere Platform Replication API
  version: v1
servers:
- url: /
tags:
- name: Platform Replication
paths:
  /api/v1/settings/ha/config/{cUUID}/backup/list:
    get:
      description: Available since YBA version 2.20.0.
      operationId: listBackups
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
      - in: query
        name: leader
        schema:
          default: 'null'
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: List backups
      tags:
      - Platform Replication
  /api/v1/settings/ha/config/{cUUID}/replication_schedule:
    get:
      operationId: getBackupInfo
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
      responses:
        default:
          content: {}
          description: successful operation
      security:
      - apiKeyAuth: []
      tags:
      - Platform Replication
      summary: Get backup info
      x-summary-source: derived
  /api/v1/settings/ha/config/{cUUID}/replication_schedule/start:
    put:
      description: Available since YBA version 2.20.0.
      operationId: startPeriodicBackup
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
      - in: query
        name: request
        schema: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlatformBackupFrequencyFormData'
        required: true
      responses:
        default:
          content: {}
          description: successful operation
      security:
      - apiKeyAuth: []
      summary: Start periodic backup
      tags:
      - Platform Replication
      x-codegen-request-body-name: PlatformBackupFrequencyRequest
  /api/v1/settings/ha/config/{cUUID}/replication_schedule/stop:
    put:
      operationId: stopPeriodicBackup
      parameters:
      - in: path
        name: cUUID
        required: true
        schema:
          format: uuid
          type: string
      - in: query
        name: request
        schema: {}
      responses:
        default:
          content: {}
          description: successful operation
      security:
      - apiKeyAuth: []
      tags:
      - Platform Replication
      summary: Stop periodic backup
      x-summary-source: derived
components:
  schemas:
    PlatformBackupFrequencyFormData:
      example:
        frequency_milliseconds: 0
      properties:
        frequency_milliseconds:
          format: int64
          type: integer
      required:
      - frequency_milliseconds
      type: object
  securitySchemes:
    apiKeyAuth:
      description: API token passed as header
      in: header
      name: X-AUTH-YW-API-TOKEN
      type: apiKey
externalDocs:
  description: About YugabyteDB Anywhere
  url: https://docs.yugabyte.com/latest/yugabyte-platform/
x-original-swagger-version: '2.0'
